### ISSUE TITLE
Subscription renewal invoices display 1st January, 1970 payment date

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-invoices#27] opened 2017-05-09 17:43 UTC
Generate an invoice for a payment that was a renewal for a Recurring Payments subscription and you end up with:

<img width="595" alt="screenshot 2017-05-09 10 40 52" src="https://cloud.githubusercontent.com/assets/2359131/25864358/fe13583e-34a3-11e7-9e0e-8a70b9ade695.png">

I've replicated the issue. Payment date displays fine on the renewal payment record itself.

Ticket: https://secure.helpscout.net/conversation/361374963/58830/?folderId=321418

**Comment by pippinsplugins** [comment] 2017-05-11 15:34
Caused by https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5729

**Comment by pippinsplugins** [comment] 2017-05-11 15:38
@SDavisMedia PR submitted on core issue. Can you confirm that fixes it for me?

**Comment by pippinsplugins** [comment] 2017-05-11 17:04
Had another test on core. Closing here. Re-open if discovered to still not be fixed.

**Comment by SDavisMedia** [comment] 2017-05-11 17:27
@pippinsplugins I'm still able to replicate this one EDD master (yes, I pulled down). Steps to replicate:

1. purchase a subscription
2. go to the subscription record and manually record a renewal using the **Record Payment and Renew Subscription** button
3. generate an invoice from purchase history for that renewal payment

from there... I'm still getting the 1970 date

**Comment by pippinsplugins** [comment] 2017-05-17 23:41
Bah. Found it. PR: https://github.com/easydigitaldownloads/edd-invoices/pull/32

**Closed** 2017-05-17 23:50 UTC
Labels: bug

**Comment by SDavisMedia** [comment] 2017-05-18 03:44
Definitely fixed. Thanks!
